### ISSUE TITLE
代码并没有mobilenetv3啊？

### ISSUE THREAD

**Issue by hyaihjq** [zihaozhang9/pytorch_yolo#1]

**Comment by zihaozhang9** [comment]
？Please describe the problem in detail.[mobilenetv3](https://github.com/zihaozhang9/pytorch_yolo/blob/master/mobilenetv3.py)

**Comment by hyaihjq** [comment]
> ？Please describe the problem in detail.[mobilenetv3](https://github.com/zihaozhang9/pytorch_yolo/blob/master/mobilenetv3.py)

从你的代码中看，暂时没有实现mobilenetv3+yolov3训练

**Comment by zihaozhang9** [comment]
Yes. I didn't update the code. You can modify it [here](https://github.com/zihaozhang9/pytorch_yolo/blob/master/main.py#L54).
Use [mobilenetv3](https://github.com/zihaozhang9/pytorch_yolo/blob/master/mobilenetv3.py#L388).
`model = Darknet(opt.cfg).to(device)
to
model = MobileNetV3_Small_yolo(opt.cfg).to(device)
`

**Comment by hyaihjq** [comment]
> Yes. I didn't update the code. You can modify it [here](https://github.com/zihaozhang9/pytorch_yolo/blob/master/main.py#L54).
> Use [mobilenetv3](https://github.com/zihaozhang9/pytorch_yolo/blob/master/mobilenetv3.py#L388).
> `model = Darknet(opt.cfg).to(device) to model = MobileNetV3_Small_yolo(opt.cfg).to(device) `

thanks, look forword to your update
